// lib/biodata-latex.ts
import { BiodataData } from './cv-types';
import { escapeLaTeX } from './latex-utils';

export function generateBiodataLatex(data: BiodataData): string {
  const pi = data.personalInfo;
  const e = escapeLaTeX;

  let tex = `% Marriage Biodata — Generated by Presume
% Compile with XeLaTeX or LuaLaTeX
\\documentclass[10.5pt,a4paper]{article}

\\usepackage[a4paper,left=1.55cm,right=1.55cm,top=1.25cm,bottom=1.25cm]{geometry}
\\usepackage{fontspec}
\\usepackage{xcolor}
\\usepackage{graphicx}
\\usepackage{tikz}
\\usepackage{tabularx}
\\usepackage{array}
\\usepackage{microtype}
\\usepackage{parskip}
\\usepackage{hyperref}
\\usepackage{setspace}

\\definecolor{accent}{HTML}{3F5F49}
\\definecolor{charcoal}{HTML}{292A28}
\\definecolor{softgray}{HTML}{666864}
\\definecolor{rulegray}{HTML}{D9DBD7}
\\definecolor{bgsoft}{HTML}{FCFBF8}

\\setmainfont{Montserrat}[Ligatures=TeX]
\\setsansfont{Lato}[Ligatures=TeX]
\\newfontfamily\\namefont{EB Garamond}[Ligatures=TeX]

\\hypersetup{colorlinks=true,urlcolor=accent,linkcolor=accent,hidelinks}

\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{0pt}
\\pagestyle{empty}
\\pagecolor{bgsoft}
\\color{charcoal}

\\newcommand{\\sectiontitle}[1]{%
  \\vspace{0.48em}%
  \\noindent{\\sffamily\\bfseries\\fontsize{7.8}{9}\\selectfont\\color{accent}\\MakeUppercase{#1}}%
  {\\color{rulegray}\\leaders\\hrule height 0.45pt\\hfill\\kern0pt}\\par
  \\vspace{0.28em}%
}
\\newcommand{\\bodytext}{\\sffamily\\fontsize{8.65}{12}\\selectfont}
\\newcommand{\\smallbody}{\\sffamily\\fontsize{8.35}{11.2}\\selectfont}
\\newcommand{\\boldlabel}[1]{{\\sffamily\\bfseries\\fontsize{8.25}{10}\\selectfont\\color{charcoal}#1}}

\\begin{document}

% ── HEADER ──────────────────────────────────────────────────────────────
\\noindent
\\begin{minipage}[c]{0.78\\textwidth}
  {\\sffamily\\bfseries\\fontsize{7.8}{9}\\selectfont\\color{accent}\\MakeUppercase{Marriage Resume}}\\\\[0.3cm]
  {\\namefont\\fontsize{28}{29}\\selectfont\\color{charcoal}${e(pi.fullName)}}\\\\[0.10em]
\\end{minipage}\\hfill
\\begin{minipage}[c]{0.18\\textwidth}
  \\centering
  \\begin{tikzpicture}
    \\clip (0,0) circle (1.12cm);
    \\fill[rulegray] (-1.12,-1.12) rectangle (1.12,1.12);
    \\node[font=\\sffamily\\fontsize{6.5}{8}\\selectfont\\color{softgray}] at (0,0) {PHOTO};
    \\draw[accent!75!black,line width=0.55pt] (0,0) circle (1.12cm);
  \\end{tikzpicture}
\\end{minipage}

\\vspace{0.38em}
{\\color{rulegray}\\hrule height 0.5pt}

% ── PERSONAL + RELIGION ─────────────────────────────────────────────────
\\begin{minipage}[t]{0.48\\textwidth}
  \\sectiontitle{Personal Information}
  \\renewcommand{\\arraystretch}{1.22}
  \\begin{tabular}{@{}>\\raggedright\\arraybackslash}p{2.35cm}p{5.0cm}@{}}
    Date of Birth & ${e(pi.dateOfBirth)}\\\\
    Age           & ${e(pi.age)}\\\\
    Height        & ${e(pi.height)}\\\\
    Blood Group   & ${e(pi.bloodGroup)}\\\\
    Marital Status & ${e(pi.maritalStatus)}\\\\
    Nationality   & ${e(pi.nationality)}\\\\
    Home District & ${e(pi.homeDistrict)}\\\\
    Current Residence & ${e(pi.currentResidence)}
  \\end{tabular}
\\end{minipage}\\hfill
`;

  if (data.enabledSections.religion) {
    tex += `\\begin{minipage}[t]{0.48\\textwidth}
  \\sectiontitle{Religious Background}
  {\\bodytext
  \\boldlabel{Religion:} ${e(data.religion)}\\\\[0.28em]
  \\boldlabel{Religious Practice:}\\\\[0.10em]
  {\\color{softgray}${e(data.religiousPractice)}}
  }
\\end{minipage}

`;
  } else {
    tex += `\\begin{minipage}[t]{0.48\\textwidth}
\\end{minipage}

`;
  }

  // ── EDUCATION ─────────────────────────────────────────────────────────
  tex += `% ── EDUCATION ───────────────────────────────────────────────────────────
\\sectiontitle{Education}
{\\bodytext
\\begin{tabularx}{\\textwidth}{@{}>\\bfseries\\color{charcoal}}l X >\\raggedleft\\arraybackslash\\color{softgray}}r@{}}
`;
  data.education.forEach((edu) => {
    tex += `${e(edu.degree)} & ${e(edu.institution)} & ${e(edu.dates)}\\\\
`;
    if (edu.thesis) {
      tex += `\\multicolumn{3}{@{}l@{}}{\\smallbody\\color{softgray}\\textit{Thesis: ${e(edu.thesis)}}}\\\\[0.30em]
`;
    }
  });
  tex += `\\end{tabularx}
}

`;

  // ── CAREER + FAMILY ───────────────────────────────────────────────────
  const showCareer = data.enabledSections.career;
  const showFamily = data.enabledSections.family;

  if (showCareer || showFamily) {
    tex += `% ── PROFESSION + FAMILY ─────────────────────────────────────────────────
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showCareer) {
      const expLines = data.careerExperience.split('\n').map(l => e(l)).join('\\\\\n  ');
      tex += `  \\sectiontitle{Profession \\& Career}
  {\\bodytext
  \\boldlabel{Experience:}\\\\[-0.02em]
  {\\color{softgray}${expLines}}\\\\[0.28em]
  \\boldlabel{Current Status:}\\\\[-0.02em]
  {\\color{softgray}${e(data.careerCurrentStatus)}}
  }
`;
    }
    tex += `\\end{minipage}\\hfill
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showFamily) {
      const fatherLines = data.fatherDetails.split('\n').map(l => e(l)).join('\\\\\n  ');
      const motherLines = data.motherDetails.split('\n').map(l => e(l)).join('\\\\\n  ');
      tex += `  \\sectiontitle{Family Background}
  {\\smallbody
  \\boldlabel{Father:}\\\\[-0.02em]
  {\\color{softgray}${fatherLines}}\\\\[0.22em]
  \\boldlabel{Mother:}\\\\[-0.02em]
  {\\color{softgray}${motherLines}}\\\\[0.22em]
  \\boldlabel{Sibling(s):}\\\\[-0.02em]
  {\\color{softgray}${e(data.siblingDetails)}}
  }
`;
    }
    tex += `\\end{minipage}

`;
  }

  // ── ABOUT ME ──────────────────────────────────────────────────────────
  if (data.enabledSections.aboutMe && data.aboutMe) {
    tex += `% ── ABOUT ME ────────────────────────────────────────────────────────────
\\sectiontitle{About Me}
{\\sffamily\\itshape\\fontsize{8.8}{12.5}\\selectfont\\color{softgray}
${e(data.aboutMe)}
}

`;
  }

  // ── LIFESTYLE + PARTNER ───────────────────────────────────────────────
  const showLifestyle = data.enabledSections.lifestyle;
  const showPartner = data.enabledSections.partnerExpectations;

  if (showLifestyle || showPartner) {
    tex += `% ── LIFESTYLE + PARTNER ─────────────────────────────────────────────────
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showLifestyle) {
      tex += `  \\sectiontitle{Lifestyle \\& Interests}
  {\\smallbody
  \\boldlabel{Interests:} {\\color{softgray}${e(data.lifestyleInterests)}}\\\\[0.18em]
  \\boldlabel{Lifestyle:} {\\color{softgray}${e(data.lifestyleDescription)}}\\\\[0.18em]
  \\boldlabel{Habits:} {\\color{softgray}${e(data.lifestyleHabits)}}\\\\[0.18em]
  \\boldlabel{Approach to Life:} {\\color{softgray}${e(data.lifestyleApproach)}}
  }
`;
    }
    tex += `\\end{minipage}\\hfill
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showPartner) {
      tex += `  \\sectiontitle{Life Partner Expectations}
  {\\smallbody\\color{softgray}
  ${e(data.partnerExpectationsText)}
  }\\\\[0.22em]
  {\\smallbody
  \\boldlabel{Education:} {\\color{softgray}${e(data.partnerEducation)}}\\\\[0.13em]
  \\boldlabel{Location:} {\\color{softgray}${e(data.partnerLocation)}}\\\\[0.13em]
  \\boldlabel{Career:} {\\color{softgray}${e(data.partnerCareer)}}
  }
`;
    }
    tex += `\\end{minipage}

`;
  }

  // ── FAMILY VALUES ─────────────────────────────────────────────────────
  if (data.enabledSections.familyValues && data.familyValues) {
    tex += `% ── FAMILY VALUES ───────────────────────────────────────────────────────
\\sectiontitle{Family Values}
{\\sffamily\\itshape\\fontsize{8.45}{11.7}\\selectfont\\color{softgray}
${e(data.familyValues)}
}

`;
  }

  // ── CUSTOM SECTIONS ───────────────────────────────────────────────────
  data.customSections.forEach(sec => {
    tex += `% ── CUSTOM: ${sec.title.toUpperCase()} ──────────────────────────────────
\\sectiontitle{${e(sec.title)}}
{\\bodytext\\color{softgray}
${e(sec.content)}
}

`;
  });

  // ── ONLINE + CONTACT ──────────────────────────────────────────────────
  const showOnline = data.enabledSections.onlinePresence && data.onlinePresence.length > 0;
  const showContact = data.enabledSections.contactPersons && data.contactPersons.length > 0;

  if (showOnline || showContact) {
    tex += `% ── ONLINE + CONTACT ────────────────────────────────────────────────────
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showOnline) {
      tex += `  \\sectiontitle{Online Presence}
  {\\smallbody
`;
      data.onlinePresence.forEach((link, idx) => {
        tex += `  \\boldlabel{${e(link.platform)}:} {\\color{accent}\\href{${link.url}}{${e(link.displayUrl)}}}`;
        tex += idx < data.onlinePresence.length - 1 ? `\\\\[0.12em]\n` : `\n`;
      });
      tex += `  }
`;
    }
    tex += `\\end{minipage}\\hfill
\\begin{minipage}[t]{0.48\\textwidth}
`;
    if (showContact) {
      tex += `  \\sectiontitle{For Further Communication}
  {\\smallbody
`;
      data.contactPersons.forEach((person, idx) => {
        tex += `  \\boldlabel{${e(person.name)}} {\\color{softgray} \\textperiodcentered{} ${e(person.relation)} \\textperiodcentered{} ${e(person.phone)}}`;
        tex += idx < data.contactPersons.length - 1 ? `\\\\[0.16em]\n` : `\n`;
      });
      tex += `  }
`;
    }
    tex += `\\end{minipage}

`;
  }

  tex += `\\end{document}
`;
  return tex;
}
